### ISSUE TITLE
Recipe App: Kanban Board Setup

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/Recipe-App#11]
Hello reviewer, we are done setting up the Kanban board for our capstone. Here are some details for you:
- [The link tou our project](https://github.com/users/patriciachrysy/projects/3)
- The are 2 people in our team: @zhorabay is Team Member 1 and @patriciachrysy is team member 2

**Comment by zeff96** [comment]
### Status: CHANGES REQUIRED ♻️
Hi @patriciachrysy and @zhorabay , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp?cid=ecf05e47yr4pnic6q9shbiwtcq4mpfjz9rvjsorxx2zmfqh9&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: Fairly distributed workload

## Required Changes ♻️

- [ ] Hello, great work, kindly make sure to add in Review column to the kanban board
![Screenshot from 2023-12-18 14-16-24](https://github.com/patriciachrysy/Recipe-App/assets/112261237/283d5537-39b6-4a72-a8e2-d7aa8ec68f93)

- [ ] Kindly make sure that below attached screenshot of the project is also added to the kanban

![Screenshot from 2023-12-18 14-26-30](https://github.com/patriciachrysy/Recipe-App/assets/112261237/9f601f2a-6765-45ab-b3f2-085eb10f86ed)

- [ ] Hello, when adding the missing requirements to the kanban, pay attention to points and make sure the gap between members is not >=5, you can achieve this by tallying each member's point and check the difference, lets make collaboration fun to all.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @patriciachrysy and @zhorabay,

✔️ Kanban columns are complete

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
